version: '3.8'

services:
  db:
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    image: postgres:15.0-alpine3.16
  api:
    container_name: url-shorter
    # env_file: .env
    build:
      context: ./
    image: sample:zero
    depends_on:
      - db
    ports:
      - 3333:3333
    environment:
      DB_HOST: db
      ARD: :5434
      USR: admin
      PASS: root
      DB: postgres
    links:
      - db
volumes:
  db:
    driver: local
